### ISSUE TITLE
Web Hook Not Receiving on Creation

### ISSUE THREAD

**Issue by biplob86429** [chrishubert/whatsapp-web-api#13]
When I run http://localhost:3000/api/startSession/ABCD QR not Received in Callback. but response showing `{"success":true,"message":"Session initiated successfully"}`
Please guide me how i can solve the issue.

I setup ENV in Production like Below - 

```
# Application
PORT=3000 # OPTIONAL
API_KEY=your_global_api_key_here # OPTIONAL
BASE_WEBHOOK_URL=https://webhook.site/9d706220-f9cb-4a59-97c9-09bcfa6caccd # MANDATORY
ENABLE_LOCAL_CALLBACK_EXAMPLE=FALSE # OPTIONAL, NOT RECOMMENDED FOR PRODUCTION
MAX_ATTACHMENT_SIZE=10000000 # IN BYTES
```

**Comment by chrishubert** [comment]
@biplob86429 
When you perform the API call `GET:http://localhost:3000/api/startSession/ABCD` it will only create the session that will hold the WhatsApp client, it doesn't return the QR code directly.

The callback data with the QR Code will be sent to the `BASE_WEBHOOK_URL`  (`https://webhook.site/9d706220-f9cb-4a59-97c9-09bcfa6caccd` in your case).
It will hold the following data: 
```
{
    "dataType": "qr",
    "data": {
        "qr": "2@4ljtzSOPWi2zwHK07zZ89+dVu08ptp3jLqYOH6e4teDiJY3HnDd78Muea0Qf5MgHsQ80vj3Iqbjnpg==,ZB1R1Hsh6d4gc0FyXTy7Vy4hD8XZCATPc5sJbrRMtkU=,rLQsvJA/65qfMNhMPoH/JQzT9+r0ETCpNjRJMM+ZDT4=,Yy9ezJhObfq9KKEexHzFWd4OsrI7aSM1U2Gxl6LgH1g=,1"
    },
    "sessionId": "ABCD"
}
```
From there you can generate the QR code from `data.qr` by using any QR code generator (https://www.nayuki.io/page/qr-code-generator-library for example) 

Feel free to close the issue if that solves your problem

**Comment by biplob86429** [comment]
Sir, 
When I hit the URL
http://localhost:3000/api/startSession/ABCD

Response NOT receive in my Call back URL. No data receive. 

Please tell me I have made any mistakes on env.

**Comment by chrishubert** [comment]
It seems you are trying to run from NPM. If you have issues, I would recommend using the docker image instead.
Modify the `docker-compose.yml` file with the following:

```
version: '3.8'

services:
  app:
    container_name: whatsapp_web_api
    image: chrishubert/whatsapp-web-api:latest # Pull the image from Docker Hub
    # restart: always
    ports:
      - "3000:3000"
    environment:
      # - API_KEY=your_global_api_key_here  # OPTIONAL
      - BASE_WEBHOOK_URL=https://webhook.site/9d706220-f9cb-4a59-97c9-09bcfa6caccd
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=FALSE # OPTIONAL, NOT RECOMMENDED FOR PRODUCTION
      - MAX_ATTACHMENT_SIZE=5000000 # IN BYTES
    volumes:
      - ./sessions:/usr/src/app/sessions # Mount the local ./sessions/ folder to the container's /usr/src/app/sessions folder
```
Then run `docker-compose up` from the same folder

I tried your webhook, it seems fine from my side:
https://webhook.site/#!/9d706220-f9cb-4a59-97c9-09bcfa6caccd/06f2a217-3dd0-419f-a55f-b86442e9b582/1
